# Generated by Django 4.2.18 on 2025-01-14 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('equipamiento', models.TextField()),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('fecha_reserva', models.DateTimeField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('estado', models.CharField(choices=[{'Confirmada', 'confirmada'}, {'Pendiente', 'pendiente'}, {'Cancelada', 'cancelada'}], max_length=50)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.salamodel')),
            ],
        ),
    ]
