# Generated by Django 4.2.18 on 2025-01-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservamodel',
            name='fecha_reserva',
            field=models.DateField(),
        ),
    ]
