# Generated by Django 4.2.18 on 2025-01-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reservamodel_fecha_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservamodel',
            name='estado',
            field=models.CharField(choices=[('Confirmada', 'Confirmada'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada')], max_length=50),
        ),
    ]
