# Generated by Django 4.2.18 on 2025-01-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reservamodel_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salamodel',
            name='disponibilidad',
        ),
    ]
